[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "template"
# The game's title. This will show up in the tile bar of your executable.
title = "template"
version = "0.1.0"
authors = ["kc00l andrea.damico@gmail.com"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "5.17"
edition = "standard"

[dependencies]
draco = "0.6.1"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "https://kc00l.itch.io/my-game"
# Your username on Itch.io.
username = "kc00l"
